# Generated by Django 5.2.3 on 2025-10-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('progrmamming', 'Programming'), ('design', 'Design'), ('personal', 'Personal'), ('business', 'Business'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
