# Generated by Django 5.2.3 on 2025-10-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0002_remove_topic_progress_remove_topic_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
