# Generated by Django 5.2.3 on 2026-01-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0004_log_created_at_log_updated_at_topic_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='topic',
            name='start_date',
            field=models.DateField(),
        ),
    ]
